name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src/github.com/heimweh/go-pagerduty/

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - run: |
          export GOPATH=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/src/github.com/heimweh/go-pagerduty/
          go vet ./...
          go test -v ./...
